/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.Dialog;

import BUS.BUSManager;
import DTO.HoaDonDTO;
import DTO.ThuocDTO;
import DTO.ChiTietHdDTO;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JWindow;
import javax.swing.ListSelectionModel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author admin
 */
public class EditThuocInCTHDDialog extends javax.swing.JDialog {

    private HoaDonDTO hoaDon;
    private ThuocDTO thuoc;
    private int sl;
    private ArrayList<ThuocDTO> listThuoc;
    
    private JWindow suggestionWindow;
    private JList<String> suggestionList;
    
    private boolean saved;

    public EditThuocInCTHDDialog(java.awt.Frame parent, HoaDonDTO hd, ThuocDTO thuoc, int soLuong) {
        super(parent, "Sửa Thuốc", true);
        this.hoaDon = hd;
        this.thuoc = thuoc;
        this.sl = soLuong;
        listThuoc = BUSManager.thuocBUS.getListThuoc();
        initComponents();
        
        createUI();
        tfThuoc.setText(thuoc.getTenThuoc());
        tfMaLH.setText(BUSManager.loHangBUS.getMaLhByMaThuoc(thuoc.getMaThuoc())+ "");
        tfSoLuong.setText(sl + "");
        
        setLocationRelativeTo(parent);
    }
    public boolean isSaved() {return saved;}
    private void createUI() {
        suggestionList = new JList<>();
        suggestionList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        JScrollPane scroll = new JScrollPane(suggestionList);
        scroll.setBorder(BorderFactory.createLineBorder(Color.GRAY));

        suggestionWindow = new JWindow(this);
        suggestionWindow.getContentPane().add(scroll);

        tfThuoc.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) { showSuggestions(); }
            @Override
            public void removeUpdate(DocumentEvent e) { showSuggestions(); }
            @Override
            public void changedUpdate(DocumentEvent e) {}
        });

        suggestionList.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                if (suggestionList.getSelectedValue() != null) {
                    tfThuoc.setText(suggestionList.getSelectedValue());
                    suggestionWindow.setVisible(false); // chỉ ẩn khi chọn
                }
            }
        });

        // Xử lý ESC để tắt popup
        tfThuoc.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ESCAPE) {
                    suggestionWindow.setVisible(false);
                }
            }
        });
    }

    private void showSuggestions() {
        // Nếu text field chưa được hiển thị -> bỏ qua
        if (!tfThuoc.isShowing()) {
            return;
        }

        String text = tfThuoc.getText().trim().toLowerCase();
        DefaultListModel<String> model = new DefaultListModel<>();
        for (ThuocDTO t : listThuoc) {
            if (t.getTenThuoc().toLowerCase().contains(text)) {
                model.addElement(t.getTenThuoc());
            }
        }

        if (model.isEmpty()) {
            suggestionWindow.setVisible(false);
            return;
        }

        suggestionList.setModel(model);
        suggestionList.setVisibleRowCount(Math.min(5, model.size())); // show tối đa 5 dòng

        try {
            Point p = tfThuoc.getLocationOnScreen();
            suggestionWindow.pack(); // cập nhật lại kích thước dựa trên số item
            suggestionWindow.setLocation(p.x, p.y + tfThuoc.getHeight());
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        suggestionWindow.setVisible(true);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlInfo = new javax.swing.JPanel();
        lblGiaTri = new javax.swing.JLabel();
        tfThuoc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfMaLH = new javax.swing.JTextField();
        btnHuy = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        pnlNgayBD = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tfSoLuong = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SỬA THUỐC");
        jLabel1.setOpaque(true);

        lblGiaTri.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGiaTri.setText("Thuốc:");

        tfThuoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Mã lô hàng:");

        tfMaLH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnHuy.setBackground(new java.awt.Color(255, 0, 0));
        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setText("HỦY");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnLuu.setBackground(new java.awt.Color(51, 255, 0));
        btnLuu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnLuu.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu.setText("LƯU");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNgayBDLayout = new javax.swing.GroupLayout(pnlNgayBD);
        pnlNgayBD.setLayout(pnlNgayBDLayout);
        pnlNgayBDLayout.setHorizontalGroup(
            pnlNgayBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlNgayBDLayout.setVerticalGroup(
            pnlNgayBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Số lượng:");

        tfSoLuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout pnlInfoLayout = new javax.swing.GroupLayout(pnlInfo);
        pnlInfo.setLayout(pnlInfoLayout);
        pnlInfoLayout.setHorizontalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlInfoLayout.createSequentialGroup()
                        .addGap(0, 98, Short.MAX_VALUE)
                        .addComponent(btnHuy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInfoLayout.createSequentialGroup()
                        .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGiaTri, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfThuoc, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(tfMaLH)
                            .addComponent(pnlNgayBD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfSoLuong))))
                .addGap(37, 37, 37))
        );
        pnlInfoLayout.setVerticalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGiaTri, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfMaLH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLuu)
                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93)
                .addComponent(pnlNgayBD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // 1️⃣ Lấy và kiểm tra dữ liệu đầu vào
        String tenThuoc = tfThuoc.getText().trim();
        String soLuongStr = tfSoLuong.getText().trim();

        if (tenThuoc.isEmpty() || soLuongStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ tên thuốc và số lượng.", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int soLuong;
        try {
            soLuong = Integer.parseInt(soLuongStr);
            if (soLuong <= 0) {
                JOptionPane.showMessageDialog(this, "Số lượng phải lớn hơn 0.", "Thông báo", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Số lượng không hợp lệ.", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2️⃣ Tìm thuốc mới trong danh sách
        ThuocDTO selectedThuoc = null;
        for (ThuocDTO t : listThuoc) {
            if (t.getTenThuoc().equalsIgnoreCase(tenThuoc)) {
                selectedThuoc = t;
                break;
            }
        }

        if (selectedThuoc == null) {
            JOptionPane.showMessageDialog(this, "Thuốc không tồn tại trong danh mục.", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 3️⃣ Lấy các mã liên quan
        int maHd = hoaDon.getMaHd();
        int maLhMoi = BUSManager.loHangBUS.getMaLhByMaThuoc(selectedThuoc.getMaThuoc());
        int maThuocCu = thuoc.getMaThuoc();
        int maLhCu = BUSManager.loHangBUS.getMaLhByMaThuoc(maThuocCu);

        // 4️⃣ Nếu đổi sang thuốc khác
        boolean doiThuoc = (selectedThuoc.getMaThuoc() != maThuocCu);

        ChiTietHdDTO chiTiet = new ChiTietHdDTO();
        chiTiet.setMaHd(maHd);
        chiTiet.setMaLh(maLhMoi);
        chiTiet.setMaThuoc(selectedThuoc.getMaThuoc());
        chiTiet.setSoLuong(soLuong);
        chiTiet.setDonGia(selectedThuoc.getGia());

        // 5️⃣ Xử lý tùy theo trường hợp
        if (doiThuoc) {
            // Đổi sang thuốc khác → kiểm tra xem thuốc mới đã tồn tại trong CTHD chưa
            boolean tonTaiThuocMoi = BUSManager.chiTietHdBUS.existsCTHD(maHd, maLhMoi, selectedThuoc.getMaThuoc());

            if (tonTaiThuocMoi) {
                JOptionPane.showMessageDialog(this, "Thuốc mới đã tồn tại trong hóa đơn, vui lòng chọn thuốc khác.", "Thông báo", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Xóa thuốc cũ trước để tránh trùng khóa
            BUSManager.chiTietHdBUS.deleteChiTietHd(maHd, maLhCu, maThuocCu);

            // Thêm bản ghi mới
            if (BUSManager.chiTietHdBUS.addChiTietHd(chiTiet)) {
                JOptionPane.showMessageDialog(this, "Cập nhật thuốc thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                saved = true;
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Không thể thêm thuốc mới!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            // Cùng thuốc, chỉ cập nhật số lượng và đơn giá
            if (BUSManager.chiTietHdBUS.updateChiTietHd(chiTiet)) {
                JOptionPane.showMessageDialog(this, "Cập nhật thuốc thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                saved = true;
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_btnLuuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditThuocInCTHDDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditThuocInCTHDDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditThuocInCTHDDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditThuocInCTHDDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditThuocInCTHDDialog dialog = new EditThuocInCTHDDialog(new javax.swing.JFrame(), new HoaDonDTO(), new ThuocDTO(), -1);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblGiaTri;
    private javax.swing.JPanel pnlInfo;
    private javax.swing.JPanel pnlNgayBD;
    private javax.swing.JTextField tfMaLH;
    private javax.swing.JTextField tfSoLuong;
    private javax.swing.JTextField tfThuoc;
    // End of variables declaration//GEN-END:variables
}
