/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Admin
 */

import com.formdev.flatlaf.*;
import com.formdev.flatlaf.extras.*;
import javax.swing.*;
import javax.swing.table.*;
import java.util.*;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import javax.swing.event.DocumentEvent;
import java.io.FileOutputStream;
import java.io.IOException;

import DTO.DanhMucThuocDTO;
import BUS.DanhMucThuocBUS;


public class DanhMucThuocForm1 extends javax.swing.JFrame {

    /**
     * Creates new form DanhMucThuocForm1
     */
    public DanhMucThuocForm1() {
        initComponents();
        load_Table();
        findRealTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhMuc = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton_Them = new javax.swing.JButton();
        jButton_Sua = new javax.swing.JButton();
        jButton_Xoa = new javax.swing.JButton();
        jButton_Export = new javax.swing.JButton();
        jTextField_TimKiem = new javax.swing.JTextField();
        jButton_Refresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách mục thuốc ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        tblDanhMuc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblDanhMuc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã danh mục thuốc", "Tên danh mục thuốc "
            }
        ));
        tblDanhMuc.setShowHorizontalLines(true);
        tblDanhMuc.setShowVerticalLines(true);
        jScrollPane1.setViewportView(tblDanhMuc);

        jPanel2.setBackground(new java.awt.Color(78, 245, 209));

        jLabel1.setBackground(new java.awt.Color(78, 245, 209));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("DANH MỤC THUỐC");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(557, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(548, 548, 548))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton_Them.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Them.setText("Thêm");
        jButton_Them.putClientProperty(FlatClientProperties.STYLE, ""
            + "background: #FFFFFF;"
            + "borderWidth: 0;"
            + "focusWidth: 0;"
            + "innerFocusWidth: 0;"
            + "shadowWidth: 0;"
            + "arc: 8;"
            + "selectedBackground: #EBEBEB;");
        jButton_Them.setIcon(new FlatSVGIcon("image/add.svg", 50, 50));
        jButton_Them.setHorizontalTextPosition(SwingConstants.CENTER);
        jButton_Them.setVerticalTextPosition(SwingConstants.BOTTOM);
        jButton_Them.setHorizontalAlignment(SwingConstants.CENTER);
        jButton_Them.setIconTextGap(5);
        jButton_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThemActionPerformed(evt);
            }
        });

        jButton_Sua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Sua.setText("Sửa");
        jButton_Sua.putClientProperty(FlatClientProperties.STYLE, ""
            + "background: #FFFFFF;"
            + "borderWidth: 0;"
            + "focusWidth: 0;"
            + "innerFocusWidth: 0;"
            + "shadowWidth: 0;"
            + "arc: 8;"
            + "selectedBackground: #EBEBEB;");
        jButton_Sua.setIcon(new FlatSVGIcon("image/update.svg", 50, 50));
        jButton_Sua.setHorizontalTextPosition(SwingConstants.CENTER);
        jButton_Sua.setVerticalTextPosition(SwingConstants.BOTTOM);
        jButton_Sua.setHorizontalAlignment(SwingConstants.CENTER);
        jButton_Sua.setIconTextGap(5);
        jButton_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SuaActionPerformed(evt);
            }
        });

        jButton_Xoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Xoa.setText("Xóa");
        jButton_Xoa.putClientProperty(FlatClientProperties.STYLE, ""
            + "background: #FFFFFF;"
            + "borderWidth: 0;"
            + "focusWidth: 0;"
            + "innerFocusWidth: 0;"
            + "shadowWidth: 0;"
            + "arc: 8;"
            + "selectedBackground: #EBEBEB;");
        jButton_Xoa.setIcon(new FlatSVGIcon("image/delete.svg", 50, 50));
        jButton_Xoa.setHorizontalTextPosition(SwingConstants.CENTER);
        jButton_Xoa.setVerticalTextPosition(SwingConstants.BOTTOM);
        jButton_Xoa.setHorizontalAlignment(SwingConstants.CENTER);
        jButton_Xoa.setIconTextGap(5);
        jButton_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_XoaActionPerformed(evt);
            }
        });

        jButton_Export.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Export.setText("Xuất file");
        jButton_Export.putClientProperty(FlatClientProperties.STYLE, ""
            + "background: #FFFFFF;"
            + "borderWidth: 0;"
            + "focusWidth: 0;"
            + "innerFocusWidth: 0;"
            + "shadowWidth: 0;"
            + "arc: 8;"
            + "selectedBackground: #EBEBEB;");
        jButton_Export.setIcon(new FlatSVGIcon("image/export.svg", 50, 50));
        jButton_Export.setHorizontalTextPosition(SwingConstants.CENTER);
        jButton_Export.setVerticalTextPosition(SwingConstants.BOTTOM);
        jButton_Export.setHorizontalAlignment(SwingConstants.CENTER);
        jButton_Export.setIconTextGap(5);
        jButton_Export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExportActionPerformed(evt);
            }
        });

        jTextField_TimKiem.putClientProperty(
            FlatClientProperties.TEXT_FIELD_LEADING_ICON,
            new FlatSVGIcon("image/search.svg", 20, 20)
        );
        jTextField_TimKiem.putClientProperty(
            FlatClientProperties.PLACEHOLDER_TEXT,
            "Tìm kiếm ..."
        );
        jTextField_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_TimKiemActionPerformed(evt);
            }
        });

        jButton_Refresh.setIcon(new FlatSVGIcon("image/reload.svg", 30, 30));
        jButton_Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButton_Export, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152)
                .addComponent(jTextField_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jButton_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton_Export, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThemActionPerformed
        // TODO add your handling code here:
        ThemDanhMucThuoc add = new ThemDanhMucThuoc();
//        add.addWindowListener(new java.awt.event.WindowAdapter() {
//            @Override
//            public void windowClosed(java.awt.event.WindowEvent e) {
//                load_Table();
//            }
//        }); 
        add.setVisible(true);
    }//GEN-LAST:event_jButton_ThemActionPerformed

    private void jButton_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SuaActionPerformed
        // TODO add your handling code here:
        int isSelected = tblDanhMuc.getSelectedRow();
        if(isSelected == -1){
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn 1 dòng dữ liệu");
            return;
        }
        
        int ma_DMT = (int)tblDanhMuc.getValueAt(isSelected, 0);
        String ten_DMT = (String)tblDanhMuc.getValueAt(isSelected, 1);
        SuaDanhMucThuoc update = new SuaDanhMucThuoc(ma_DMT, ten_DMT);
        update.setVisible(true);
    }//GEN-LAST:event_jButton_SuaActionPerformed

    private void jButton_RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RefreshActionPerformed
        // TODO add your handling code here:
        load_Table();
    }//GEN-LAST:event_jButton_RefreshActionPerformed

    private void jTextField_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_TimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_TimKiemActionPerformed

    private void jButton_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XoaActionPerformed
        // TODO add your handling code here:
        int isSelected = tblDanhMuc.getSelectedRow();
        if(isSelected == -1){
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn 1 dòng dữ liệu");
            return;
        }
        
        int ma_DMT = (int)tblDanhMuc.getValueAt(isSelected, 0);
        
        boolean flag = DanhMucThuocBUS.getInstance().deleteDanhMucThuoc(ma_DMT);
        if (flag) {
            JOptionPane.showMessageDialog(rootPane, "Xóa danh mục thuốc thành công");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Xóa danh mục thuốc thất bại");
        }
    }//GEN-LAST:event_jButton_XoaActionPerformed

    private void jButton_ExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExportActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Chọn nơi lưu file Excel");
        int userSelection = fileChooser.showSaveDialog(this);
        
        if(userSelection == JFileChooser.APPROVE_OPTION){
            String filePath = fileChooser.getSelectedFile().getAbsolutePath();
            if (!filePath.endsWith(".xlsx")){
                filePath += ".xlsx";
            }
            export(tblDanhMuc, filePath);
        }
    }//GEN-LAST:event_jButton_ExportActionPerformed

    private void export(JTable jTable, String filePath){
        try(Workbook workbook = new XSSFWorkbook()){
            Sheet sheet = workbook.createSheet("Danh sách khách hàng");
            TableModel model = jTable.getModel();
            
            Row header = sheet.createRow(0);
            for (int i = 0; i < model.getColumnCount(); i++) {
                Cell cell = header.createCell(i);
                cell.setCellValue(model.getColumnName(i));
            }
        
            for(int i = 0; i < model.getRowCount(); i++){
                Row row = sheet.createRow(i+1);
                for(int j = 0; j < model.getColumnCount(); j++){
                    Object value = model.getValueAt(i, j);
                    row.createCell(j).setCellValue(value != null ? value.toString() : "");
                }
            }
            try(FileOutputStream fos = new FileOutputStream(filePath)){
                workbook.write(fos);
            }
            
            JOptionPane.showMessageDialog(null, "Xuất file Excel thành công");
        }catch(IOException  ex){
            System.err.println("LỖI Ở HÀM exportToExcel(), ExportDataToExcel.java");
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Lỗi xuất file Excel");
        }
    }
    
    private void load_Table(){
        DefaultTableModel model = (DefaultTableModel)tblDanhMuc.getModel();
        model.setRowCount(0);
        ArrayList<DanhMucThuocDTO> list_DMT = DanhMucThuocBUS.getInstance().getListDanhMucThuoc();
        for (DanhMucThuocDTO dmt : list_DMT){
            Object[] row = {
                dmt.getMaDmt(),
                dmt.getTenDmt()
            };
            model.addRow(row);
        }
    }
    
    private void findRealTime(){
        DefaultTableModel model = (DefaultTableModel)tblDanhMuc.getModel();
        TableRowSorter<DefaultTableModel> sorted = new TableRowSorter<>(model);
        tblDanhMuc.setRowSorter(sorted);
        
        jTextField_TimKiem.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                filter();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                filter();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                filter();
            }
            
            private void filter(){
                String keyword = jTextField_TimKiem.getText().trim();
                if(keyword.isEmpty()){
                    sorted.setRowFilter(null);
                }else{
                    java.util.List<RowFilter<Object, Object>> filters = new ArrayList<>();
                    filters.add(RowFilter.regexFilter("(?i)" + keyword, 0));                    
                    filters.add(RowFilter.regexFilter("(?i)" + keyword, 1));
                    sorted.setRowFilter(RowFilter.orFilter(filters));
                }
            }
        });
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DanhMucThuocForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DanhMucThuocForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DanhMucThuocForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DanhMucThuocForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        */
        //</editor-fold>

        try{
            javax.swing.UIManager.setLookAndFeel(new FlatLightLaf());
        }catch (Exception ex){
            ex.printStackTrace();
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DanhMucThuocForm1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Export;
    private javax.swing.JButton jButton_Refresh;
    private javax.swing.JButton jButton_Sua;
    private javax.swing.JButton jButton_Them;
    private javax.swing.JButton jButton_Xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField_TimKiem;
    private javax.swing.JTable tblDanhMuc;
    // End of variables declaration//GEN-END:variables
}
