/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.*;
// import com.formdev.flatlaf.*;

import BUS.BUSManager;
import DTO.KhachHangDTO;
import DTO.NhanVienDTO;
import test.ThuocGUI;

import java.awt.Image;
import java.awt.event.ActionEvent;

/**
 *
 * @author aries
 */
public class LoginForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(LoginForm.class.getName());

    /**
     * Creates new form Login
     */
    public LoginForm() {
        initComponents();

        // bind phím mũi tên cho field
        jTextField_TaiKhoan.getInputMap(JComponent.WHEN_FOCUSED).put(KeyStroke.getKeyStroke("DOWN"), "moveDown");
        jTextField_TaiKhoan.getActionMap().put("moveDown", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jPasswordField1.requestFocusInWindow();
            }
        });
        jPasswordField1.getInputMap(JComponent.WHEN_FOCUSED).put(KeyStroke.getKeyStroke("UP"), "moveUp");
        jPasswordField1.getActionMap().put("moveUp", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jTextField_TaiKhoan.requestFocusInWindow();
            }
        });

        // bind enter cho password field
        jPasswordField1.getInputMap(JComponent.WHEN_FOCUSED).put(KeyStroke.getKeyStroke("ENTER"), "enterPressed");
        jPasswordField1.getActionMap().put("enterPressed", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // dùng chung với button đăng nhập
                jButton_DangNhapActionPerformed(e);
            }
        });

        jPasswordField1.putClientProperty("JPasswordField.showRevealButton", true);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_DangNhap = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel_TaiKhoan = new javax.swing.JLabel();
        jTextField_TaiKhoan = new javax.swing.JTextField();
        jLabel_MatKhau = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        ImageIcon icon = new ImageIcon(getClass().getResource("/image/pharmacy.png"));
        int width = 500;
        int height = 500;
        Image img = icon.getImage();
        Image scaledImg = img.getScaledInstance(width, height, Image.SCALE_SMOOTH);
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_DangNhap.setBackground(new java.awt.Color(0, 204, 204));
        jButton_DangNhap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_DangNhap.setForeground(new java.awt.Color(255, 255, 255));
        jButton_DangNhap.setText("Đăng Nhập");
        jButton_DangNhap.putClientProperty("JButton.buttonType", "roundRect");
        jButton_DangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DangNhapActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ĐĂNG NHẬP");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel_TaiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_TaiKhoan.setText("Tài Khoản");
        jLabel_TaiKhoan.setPreferredSize(new java.awt.Dimension(53, 20));

        jTextField_TaiKhoan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_TaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_TaiKhoanActionPerformed(evt);
            }
        });

        jLabel_MatKhau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_MatKhau.setText("Mật Khẩu");

        jPasswordField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel_TaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton_DangNhap, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel_MatKhau, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField_TaiKhoan)
                                        .addComponent(jPasswordField1)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                jPanel1Layout.createSequentialGroup()
                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap()));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(jLabel_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_MatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(jButton_DangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(110, Short.MAX_VALUE)));

        jLabel2.setIcon(new ImageIcon(scaledImg));
        jLabel2.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                                .addGap(55, 55, 55)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap(42, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_TaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_TaiKhoanActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField_TaiKhoanActionPerformed

    private void jButton_DangNhapActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_DangNhapActionPerforme
        String username = jTextField_TaiKhoan.getText();
        String password = new String(jPasswordField1.getPassword());

        Object user = BUSManager.taiKhoanBUS.login(username, password);

        if (user == null) {
            JOptionPane.showMessageDialog(this, "Sai Mật Khẩu Hoặc Tài Khoản", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Phân biệt loại người dùng
        if (user instanceof NhanVienDTO nv) {

            // phân biệt giới hạn quyền
            if (BUSManager.taiKhoanBUS.getTaiKhoanByMaTk(nv.getMaTk()).getVaiTro().equals("admin")) {
                // chuyển trang admin
                JOptionPane.showMessageDialog(this, "Chào admin: " + username);
                SwingUtilities.invokeLater(() -> {
                    new AdminLayout().setVisible(true);
                });
            } else {
                // chuyển trang nhân viên
                JOptionPane.showMessageDialog(this, "Chào nhân viên: " + username);
                SwingUtilities.invokeLater(() -> {
                    new NhanVienLayout().setVisible(true);
                });

            }

            // this.setVisible(false);
            this.dispose();
        } else if (user instanceof KhachHangDTO) {
            JOptionPane.showMessageDialog(this, "Chào khách hàng: " + username);

            // chuyển trang khách hàng
            SwingUtilities.invokeLater(() -> {
                new KhachHangForm().setVisible(true);
            });

            // this.setVisible(false);
            this.dispose();
        }
    }// GEN-LAST:event_jButton_DangNhapActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jPasswordField1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // public static void main(String args[]) {

    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    // (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default
     * look and feel.
     * For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    /*
     * try {
     * for (javax.swing.UIManager.LookAndFeelInfo info :
     * javax.swing.UIManager.getInstalledLookAndFeels()) {
     * if ("Nimbus".equals(info.getName())) {
     * javax.swing.UIManager.setLookAndFeel(info.getClassName());
     * break;
     * }
     * }
     * } catch (ReflectiveOperationException |
     * javax.swing.UnsupportedLookAndFeelException ex) {
     * logger.log(java.util.logging.Level.SEVERE, null, ex);
     * }
     * </editor-fold>
     */

    // try {
    // UIManager.setLookAndFeel(new FlatLightLaf());
    // FlatLightLaf.setup();
    // UIManager.put("PasswordField.showRevealButton", true);
    // } catch (Exception ex) {
    // ex.printStackTrace();
    // }
    // /* Create and display the form */
    // java.awt.EventQueue.invokeLater(() -> new LoginForm().setVisible(true));
    // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_DangNhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_MatKhau;
    private javax.swing.JLabel jLabel_TaiKhoan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField_TaiKhoan;
    // End of variables declaration//GEN-END:variables
}
