/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.util.List;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import javax.swing.event.DocumentEvent;
import java.io.FileOutputStream;
import java.io.IOException;

import BUS.BUSManager;
import DTO.NhanVienDTO;
import DTO.TaiKhoanDTO;
import javax.swing.JFileChooser;
import javax.swing.table.TableModel;
import utils.IconUtils;
import view.Dialog.AddNhanVienDialog;
import view.Dialog.UpdateNhanVienDialog;

/**
 *
 * @author admin
 */
public class NhanVienForm extends javax.swing.JFrame {

    /**
     * Creates new form NhanVienForm
     */
    public NhanVienForm() {
        initComponents();

        setupListNV();
        setIcons();

        // bind
        jTextField4.setText("");
        jTextField4.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                search();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                search();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                search();
            }

            private void search() {
                String text = jTextField4.getText().trim();
                if (text.isEmpty()) {
                    loadData();
                } else {
                    loadData(text);
                }
            }
        });

        // lấy data từ db
        loadData();
    }

    private void setIcons() {
        IconUtils.setIcon(magnifyingGlassLabel, "magnifying-glass.png", true);
        IconUtils.setIcon(refreshLabel, "refresh.png", true);
    }

    private void setupListNV() {
        String[] columnNames = {
                "Mã NV", "Mã TK", "Tên", "SĐT", "Ngày vào làm", "Lương", "Email", "Địa chỉ", "Giới tính", "Ngày sinh",
                "Vị trí"
        };

        Object[][] data = {
                // { "1", "11", "1", "2023-01-15", "25000000.00", "admin@store.com", "Quận 1,
                // TP.HCM", "Nam", "1990-05-10",
                // "Quản lý" },
                // { "2", "12", "2", "2024-03-01", "12000000.00", "quyen@store.com", "Quận 3,
                // TP.HCM", "Nữ", "1998-11-20",
                // "Nhân viên bán hàng" }
        };

        model = new DefaultTableModel(data, columnNames);
        table = new JTable(model);
        JScrollPane scrollPane = new JScrollPane(table);
        listNVPanel.setLayout(new BorderLayout());
        listNVPanel.add(scrollPane);

        // Chiều cao hàng
        table.setRowHeight(28);

        // Font chữ
        table.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        table.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));

        // Màu header
        table.getTableHeader().setBackground(new Color(240, 240, 240));
        table.getTableHeader().setForeground(Color.BLACK);

        // Căn giữa cột STT
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        table.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);

        // Căn phải cột "Số lượng tồn" và "Đơn giá"
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
        table.getColumnModel().getColumn(2).setCellRenderer(rightRenderer);
        table.getColumnModel().getColumn(3).setCellRenderer(rightRenderer);

        // Tự động giãn cột cho đẹp
        table.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NVPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        listNVPanel = new javax.swing.JPanel();
        searchPanel = new javax.swing.JPanel();
        refreshLabel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        magnifyingGlassLabel = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        buttonPanel = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        editButton1 = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        exportButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1350, 800));

        jLabel2.setBackground(new java.awt.Color(0, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("THÔNG TIN NHÂN VIÊN");
        jLabel2.setOpaque(true);

        javax.swing.GroupLayout listNVPanelLayout = new javax.swing.GroupLayout(listNVPanel);
        listNVPanel.setLayout(listNVPanelLayout);
        listNVPanelLayout.setHorizontalGroup(
            listNVPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        listNVPanelLayout.setVerticalGroup(
            listNVPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout NVPanelLayout = new javax.swing.GroupLayout(NVPanel);
        NVPanel.setLayout(NVPanelLayout);
        NVPanelLayout.setHorizontalGroup(
            NVPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listNVPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        NVPanelLayout.setVerticalGroup(
            NVPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NVPanelLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, Short.MAX_VALUE)
                .addGap(2, 2, 2)
                .addComponent(listNVPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        searchPanel.setBackground(new java.awt.Color(255, 255, 255));
        searchPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        refreshLabel.setText("jLabel8");

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "A - Z", "Z - A", "Giá tăng" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        magnifyingGlassLabel.setText("jLabel8");

        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField4.setText("jTextField4");
        jTextField4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(magnifyingGlassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refreshLabel)
                .addGap(37, 37, 37))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(magnifyingGlassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1)
                    .addComponent(refreshLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonPanel.setLayout(null);

        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plus.png"))); // NOI18N
        addButton.setText("them");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(addButton);
        addButton.setBounds(11, 6, 94, 53);

        editButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/wrench.png"))); // NOI18N
        editButton1.setText("sua");
        editButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButton1ActionPerformed(evt);
            }
        });
        buttonPanel.add(editButton1);
        editButton1.setBounds(111, 6, 94, 53);

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/remove.png"))); // NOI18N
        deleteButton.setText("xoa");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(deleteButton);
        deleteButton.setBounds(211, 6, 94, 53);

        exportButton.setText("export");
        exportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(exportButton);
        exportButton.setBounds(311, 6, 94, 53);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NVPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 389, Short.MAX_VALUE)
                        .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NVPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Chọn nơi lưu file Excel");
        int userSelection = fileChooser.showSaveDialog(this);
        
        if(userSelection == JFileChooser.APPROVE_OPTION){
            String filePath = fileChooser.getSelectedFile().getAbsolutePath();
            if (!filePath.endsWith(".xlsx")){
                filePath += ".xlsx";
            }
            export(this.table, filePath);
        }
    }//GEN-LAST:event_exportButtonActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jComboBox1ActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addButtonActionPerformed
        AddNhanVienDialog dialog = new AddNhanVienDialog(this);
        dialog.setVisible(true);
        loadData();
    }// GEN-LAST:event_addButtonActionPerformed

    private void export(JTable jTable, String filePath){
        try(Workbook workbook = new XSSFWorkbook()){
            Sheet sheet = workbook.createSheet("Danh sách Nhân Viên");
            TableModel model = jTable.getModel();
            
            Row header = sheet.createRow(0);
            for (int i = 0; i < model.getColumnCount(); i++) {
                Cell cell = header.createCell(i);
                cell.setCellValue(model.getColumnName(i));
            }
        
            for(int i = 0; i < model.getRowCount(); i++){
                Row row = sheet.createRow(i+1);
                for(int j = 0; j < model.getColumnCount(); j++){
                    Object value = model.getValueAt(i, j);
                    row.createCell(j).setCellValue(value != null ? value.toString() : "");
                }
            }
            try(FileOutputStream fos = new FileOutputStream(filePath)){
                workbook.write(fos);
            }
            
            JOptionPane.showMessageDialog(null, "Xuất file Excel thành công");
        }catch(IOException  ex){
            System.out.println("view.NhanVienForm.export()");
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Lỗi xuất file Excel");
        }
    }
    
    private void editButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_editButton1ActionPerformed
        int selectedRow = table.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                    "Vui lòng chọn nhân viên cần xóa!",
                    "Thông báo",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        int modelRow = table.convertRowIndexToModel(selectedRow);
        int maNv = (Integer) model.getValueAt(modelRow, 0);

        UpdateNhanVienDialog dialog = new UpdateNhanVienDialog(this, BUSManager.nhanVienBUS.getNhanVienByMaNv(maNv));
        dialog.setVisible(true);
        loadData();
    }// GEN-LAST:event_editButton1ActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deleteButtonActionPerformed
        int selectedRow = table.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                    "Vui lòng chọn nhân viên cần xóa!",
                    "Thông báo",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xoá nhân viên này?", "Xác nhận",
                JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION)
            return;

        int modelRow = table.convertRowIndexToModel(selectedRow);
        int maNv = (Integer) model.getValueAt(modelRow, 0);

        int maTk = BUSManager.nhanVienBUS.getNhanVienByMaNv(maNv).getMaTk();
        new SwingWorker<Boolean, Void>() {
            @Override
            protected Boolean doInBackground() {
                // Xóa nhân viên (await)
                boolean deletedNv = BUSManager.nhanVienBUS.deleteNhanVien(maNv);
                if (!deletedNv)
                    return false;

                // Xóa tài khoản (await)
                boolean deletedTk = BUSManager.taiKhoanBUS.deleteTaiKhoan(maTk);
                return deletedTk;
            }

            @Override
            protected void done() {
                try {
                    boolean success = get();
                    if (success) {
                        JOptionPane.showMessageDialog(null, "Đã xoá nhân viên và tài khoản thành công!");
                        loadData();
                    } else {
                        JOptionPane.showMessageDialog(null, "Không thể xoá nhân viên hoặc tài khoản!");
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Đã xảy ra lỗi!");
                }
            }

        }.execute();
    }// GEN-LAST:event_deleteButtonActionPerformed




    public void loadData() {
        model.setRowCount(0);
        List<NhanVienDTO> listNv = BUSManager.nhanVienBUS.getListNhanVien();
        List<TaiKhoanDTO> listTk = BUSManager.taiKhoanBUS.getListTaiKhoan();
        if (listNv == null || listTk == null)
            return;

        for (NhanVienDTO nv : listNv) {

            for (TaiKhoanDTO tk : listTk) {
                if (nv.getMaTk() == tk.getMaTk() && !tk.getVaiTro().equals("admin")) {
                    Object[] row = {
                            nv.getMaNv(),
                            nv.getMaTk(),
                            tk.getTen(),
                            tk.getSdt(),
                            nv.getNgayVaoLam(),
                            nv.getLuong(),
                            nv.getEmail(),
                            nv.getDiaChi(),
                            nv.getGioiTinh(),
                            nv.getNgaySinh(),
                            nv.getViTri(),
                    };
                    model.addRow(row);
                    break;
                }
            }
        }
    }

    public void loadData(String ten) {
        model.setRowCount(0);
        List<NhanVienDTO> listNv = BUSManager.nhanVienBUS.getListNhanVien();
        List<TaiKhoanDTO> listTk = BUSManager.taiKhoanBUS.getListTaiKhoan();
        if (listNv == null || listTk == null)
            return;

        for (NhanVienDTO nv : listNv) {
            for (TaiKhoanDTO tk : listTk) {
                if (nv.getMaTk() == tk.getMaTk() &&
                        tk.getTen().toLowerCase().contains(ten.toLowerCase())) {

                    Object[] row = {
                            nv.getMaNv(),
                            nv.getMaTk(),
                            tk.getTen(),
                            tk.getSdt(),
                            nv.getNgayVaoLam(),
                            nv.getLuong(),
                            nv.getEmail(),
                            nv.getDiaChi(),
                            nv.getGioiTinh(),
                            nv.getNgaySinh(),
                            nv.getViTri(),
                    };
                    model.addRow(row);
                    break;
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel NVPanel;
    private javax.swing.JButton addButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton1;
    private javax.swing.JButton exportButton;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPanel listNVPanel;
    private javax.swing.JLabel magnifyingGlassLabel;
    private javax.swing.JLabel refreshLabel;
    private javax.swing.JPanel searchPanel;
    // End of variables declaration//GEN-END:variables

    private javax.swing.JTable table;
    private javax.swing.table.DefaultTableModel model;
}
