/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.*;
import com.formdev.flatlaf.*;
import com.formdev.flatlaf.extras.*;
import java.awt.*;
import javax.swing.*;
import utils.Convert_JFrame_To_JPanel;

/**
 *
 * @author aries
 */
public class NhanVienLayout extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NhanVienLayout.class.getName());

    /**
     * Creates new form NhanVienForm
     */
    public NhanVienLayout() {
        initComponents();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        
        HoaDonForm HoaDon = new HoaDonForm();
        PhieuNhapForm PhieuNhap = new PhieuNhapForm();
        KhachHangForm KhachHang = new KhachHangForm();
        ThuocForm1 Thuoc = new ThuocForm1();
        
        jPanel3.add(Convert_JFrame_To_JPanel.get_components_from_jFrame(HoaDon), "HoaDon");
        jPanel3.add(Convert_JFrame_To_JPanel.get_components_from_jFrame(HoaDon), "PhieuNhap");
        jPanel3.add(Convert_JFrame_To_JPanel.get_components_from_jFrame(KhachHang), "KhachHang");
        jPanel3.add(Convert_JFrame_To_JPanel.get_components_from_jFrame(Thuoc), "Thuoc");
        
        // /*
        HoaDon.dispose();
        PhieuNhap.dispose();
        KhachHang.dispose();
        Thuoc.dispose();
        
        // */
        
        jPanel3.revalidate();
        jPanel3.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jToggleButton_HoaDon = new javax.swing.JToggleButton();
        jToggleButton_PhieuNhap = new javax.swing.JToggleButton();
        jToggleButton_KhachHang = new javax.swing.JToggleButton();
        jToggleButton_Thuoc = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton_DangXuat = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        buttonGroup1.add(jToggleButton_HoaDon);
        buttonGroup1.add(jToggleButton_PhieuNhap);
        buttonGroup1.add(jToggleButton_KhachHang);
        buttonGroup1.add(jToggleButton_Thuoc);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setSize(new java.awt.Dimension(1920, 1080));

        jLabel1.setBackground(new java.awt.Color(250, 250, 250));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nhân Viên");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setIcon(new FlatSVGIcon("image/employee.svg", 20, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(0, 1, 20, 20));

        jToggleButton_HoaDon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jToggleButton_HoaDon.setText("Hóa Đơn");
        jToggleButton_HoaDon.setIcon(new FlatSVGIcon("image/bill.svg", 20, 20));
        jToggleButton_HoaDon.putClientProperty(FlatClientProperties.STYLE, ""
            + "background: #FFFFFF;"
            + "borderWidth: 0;"
            + "focusWidth: 0;"
            + "innerFocusWidth: 0;"
            + "shadowWidth: 0;"
            + "arc: 8;"
            + "hoverBackground: #A8FFED;"
            + "selectedBackground: #4EF5D1;");
        jToggleButton_HoaDon.setHorizontalAlignment(SwingConstants.LEFT);
        jToggleButton_HoaDon.setHorizontalTextPosition(SwingConstants.RIGHT);
        jToggleButton_HoaDon.setIconTextGap(5);
        jToggleButton_HoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_HoaDonActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton_HoaDon);

        jToggleButton_PhieuNhap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jToggleButton_PhieuNhap.setText("Phiếu Nhập");
        jToggleButton_PhieuNhap.setIcon(new FlatSVGIcon("image/category.svg", 20, 20));
        jToggleButton_PhieuNhap.putClientProperty(FlatClientProperties.STYLE, ""
            + "background: #FFFFFF;"
            + "borderWidth: 0;"
            + "focusWidth: 0;"
            + "innerFocusWidth: 0;"
            + "shadowWidth: 0;"
            + "arc: 8;"
            + "hoverBackground: #A8FFED;"
            + "selectedBackground: #4EF5D1;");
        jToggleButton_PhieuNhap.setHorizontalAlignment(SwingConstants.LEFT);
        jToggleButton_PhieuNhap.setHorizontalTextPosition(SwingConstants.RIGHT);
        jToggleButton_PhieuNhap.setIconTextGap(5);
        jToggleButton_PhieuNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_PhieuNhapActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton_PhieuNhap);

        jToggleButton_KhachHang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jToggleButton_KhachHang.setText("Khách Hàng");
        jToggleButton_KhachHang.setIcon(new FlatSVGIcon("image/customer.svg", 20, 20));
        jToggleButton_KhachHang.putClientProperty(FlatClientProperties.STYLE, ""
            + "background: #FFFFFF;"
            + "borderWidth: 0;"
            + "focusWidth: 0;"
            + "innerFocusWidth: 0;"
            + "shadowWidth: 0;"
            + "arc: 8;"
            + "hoverBackground: #A8FFED;"
            + "selectedBackground: #4EF5D1;");
        jToggleButton_KhachHang.setHorizontalAlignment(SwingConstants.LEFT);
        jToggleButton_KhachHang.setHorizontalTextPosition(SwingConstants.RIGHT);
        jToggleButton_KhachHang.setIconTextGap(5);
        jToggleButton_KhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_KhachHangActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton_KhachHang);

        jToggleButton_Thuoc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jToggleButton_Thuoc.setText("Thuốc");
        jToggleButton_Thuoc.setIcon(new FlatSVGIcon("image/medicine.svg", 20, 20));
        jToggleButton_Thuoc.putClientProperty(FlatClientProperties.STYLE, ""
            + "background: #FFFFFF;"
            + "borderWidth: 0;"
            + "focusWidth: 0;"
            + "innerFocusWidth: 0;"
            + "shadowWidth: 0;"
            + "arc: 8;"
            + "hoverBackground: #A8FFED;"
            + "selectedBackground: #4EF5D1;");
        jToggleButton_Thuoc.setHorizontalAlignment(SwingConstants.LEFT);
        jToggleButton_Thuoc.setHorizontalTextPosition(SwingConstants.RIGHT);
        jToggleButton_Thuoc.setIconTextGap(5);
        jToggleButton_Thuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_ThuocActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton_Thuoc);

        jPanel3.setPreferredSize(new java.awt.Dimension(1350, 800));
        jPanel3.setLayout(new java.awt.CardLayout());

        jButton_DangXuat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_DangXuat.setText("Đăng Xuất");
        jButton_DangXuat.setIcon(new FlatSVGIcon("image/logout.svg", 20, 20));
        jButton_DangXuat.setHorizontalAlignment(SwingConstants.LEFT);
        jButton_DangXuat.setHorizontalTextPosition(SwingConstants.RIGHT);
        jButton_DangXuat.setIconTextGap(5);
        jButton_DangXuat.putClientProperty(FlatClientProperties.STYLE, ""
            + "background: #FFFFFF;"
            + "borderWidth: 0;"
            + "focusWidth: 0;"
            + "innerFocusWidth: 0;"
            + "shadowWidth: 0;"
            + "arc: 8;"
            + "hoverBackground: #A8FFED;");
        jButton_DangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DangXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_DangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_DangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(321, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(305, 305, 305)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator3)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addContainerGap(242, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton_HoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_HoaDonActionPerformed
        // TODO add your handling code here:
        CardLayout card_layout = (CardLayout) jPanel3.getLayout();
        card_layout.show(jPanel3, "HoaDon");
    }//GEN-LAST:event_jToggleButton_HoaDonActionPerformed

    private void jToggleButton_ThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_ThuocActionPerformed
        // TODO add your handling code here:
        CardLayout card_layout = (CardLayout) jPanel3.getLayout();
        card_layout.show(jPanel3, "Thuoc");
    }//GEN-LAST:event_jToggleButton_ThuocActionPerformed

    private void jButton_DangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DangXuatActionPerformed
        // TODO add your handling code here:
        // Lưu data xuống database
        dispose();
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_jButton_DangXuatActionPerformed

    private void jToggleButton_KhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_KhachHangActionPerformed
        // TODO add your handling code here:
        CardLayout card_layout = (CardLayout) jPanel3.getLayout();
        card_layout.show(jPanel3, "KhachHang");
    }//GEN-LAST:event_jToggleButton_KhachHangActionPerformed

    private void jToggleButton_PhieuNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_PhieuNhapActionPerformed
        // TODO add your handling code here:
        CardLayout card_layout = (CardLayout) jPanel3.getLayout();
        card_layout.show(jPanel3, "PhieuNhap");
    }//GEN-LAST:event_jToggleButton_PhieuNhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>
        try{
            javax.swing.UIManager.setLookAndFeel(new FlatLightLaf());
            
        }catch(Exception ex){
            ex.printStackTrace();
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NhanVienLayout().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_DangXuat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JToggleButton jToggleButton_HoaDon;
    private javax.swing.JToggleButton jToggleButton_KhachHang;
    private javax.swing.JToggleButton jToggleButton_PhieuNhap;
    private javax.swing.JToggleButton jToggleButton_Thuoc;
    // End of variables declaration//GEN-END:variables
}
