/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author aries
 */


import DTO.KhachHangDTO;
import DTO.NhanVienDTO;
import DTO.HoaDonDTO;
import DTO.KhuyenMaiDTO;
import DTO.TaiKhoanDTO;
import BUS.KhachHangBUS;
import BUS.NhanVienBUS;
import BUS.HoaDonBUS;
import BUS.KhuyenMaiBUS;
import BUS.TaiKhoanBUS;

import com.formdev.flatlaf.*;
import com.formdev.flatlaf.extras.*;
import javax.swing.*;
import javax.swing.table.*;
import java.util.*;

public class QuanLyHoaDon extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(QuanLyHoaDon.class.getName());

    /**
     * Creates new form QuanLyHoaDon
     */
    public QuanLyHoaDon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton_Sua = new javax.swing.JButton();
        jButton_Xoa = new javax.swing.JButton();
        jTextField_TimKiem = new javax.swing.JTextField();
        jButton_Refresh = new javax.swing.JButton();
        jButton_Export = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(78, 245, 209));

        jLabel1.setBackground(new java.awt.Color(78, 245, 209));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ HÓA ĐƠN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton_Sua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_Sua.setText("SỬA");
        jButton_Sua.putClientProperty(FlatClientProperties.STYLE, ""
            + "background: #FFFFFF;"
            + "borderWidth: 0;"
            + "focusWidth: 0;"
            + "innerFocusWidth: 0;"
            + "shadowWidth: 0;"
            + "arc: 8;"
            + "selectedBackground: #EBEBEB;");
        jButton_Sua.setIcon(new FlatSVGIcon("image/update.svg", 50, 50));
        jButton_Sua.setHorizontalTextPosition(SwingConstants.CENTER);
        jButton_Sua.setVerticalTextPosition(SwingConstants.BOTTOM);
        jButton_Sua.setHorizontalAlignment(SwingConstants.CENTER);
        jButton_Sua.setIconTextGap(5);

        jButton_Xoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_Xoa.setText("XÓA");
        jButton_Xoa.putClientProperty(FlatClientProperties.STYLE, ""
            + "background: #FFFFFF;"
            + "borderWidth: 0;"
            + "focusWidth: 0;"
            + "innerFocusWidth: 0;"
            + "shadowWidth: 0;"
            + "arc: 8;"
            + "selectedBackground: #EBEBEB;");
        jButton_Xoa.setIcon(new FlatSVGIcon("image/delete.svg", 50, 50));
        jButton_Xoa.setHorizontalTextPosition(SwingConstants.CENTER);
        jButton_Xoa.setVerticalTextPosition(SwingConstants.BOTTOM);
        jButton_Xoa.setHorizontalAlignment(SwingConstants.CENTER);
        jButton_Xoa.setIconTextGap(5);

        jTextField_TimKiem.putClientProperty(
            FlatClientProperties.TEXT_FIELD_LEADING_ICON,
            new FlatSVGIcon("image/search.svg", 20, 20)
        );
        jTextField_TimKiem.putClientProperty(
            FlatClientProperties.PLACEHOLDER_TEXT,
            "Tìm kiếm ..."
        );
        jTextField_TimKiem.putClientProperty(
            FlatClientProperties.STYLE,
            "arc: 8;"
        );

        jButton_Refresh.setIcon(new FlatSVGIcon("image/reload.svg", 30, 30));

        jButton_Export.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_Export.setText("XUẤT FILE");
        jButton_Export.putClientProperty(FlatClientProperties.STYLE, ""
            + "background: #FFFFFF;"
            + "borderWidth: 0;"
            + "focusWidth: 0;"
            + "innerFocusWidth: 0;"
            + "shadowWidth: 0;"
            + "arc: 8;"
            + "selectedBackground: #EBEBEB;");
        jButton_Export.setIcon(new FlatSVGIcon("image/export.svg", 50, 50));
        jButton_Export.setHorizontalTextPosition(SwingConstants.CENTER);
        jButton_Export.setVerticalTextPosition(SwingConstants.BOTTOM);
        jButton_Export.setHorizontalAlignment(SwingConstants.CENTER);
        jButton_Export.setIconTextGap(5);
        jButton_Export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton_Export, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_Export, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_Sua, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                        .addComponent(jButton_Xoa, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã HĐ", "Nhân Viên", "Khách Hàng", "Khuyến Mãi", "Tổng tiền", "Ngày Xuất", "PTTT"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ExportActionPerformed

    
    private void loadTable(){
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        ArrayList<HoaDonDTO> list_hd = HoaDonBUS.getInstance().getListHoaDon();
        ArrayList<KhachHangDTO> list_kh = KhachHangBUS.getInstance().getListKhachHang();
        ArrayList<NhanVienDTO> list_nv = NhanVienBUS.getInstance().getListNhanVien();
        ArrayList<KhuyenMaiDTO> list_km = KhuyenMaiBUS.getInstance().getListKhuyenMai();
        
        for(HoaDonDTO hd: list_hd){
            int ma_tk_kh = KhachHangBUS.getInstance().getKhachHangByMaKh(hd.getMaKh()).getMaTk();
            int ma_tk_nv = NhanVienBUS.getInstance().getNhanVienByMaNv(hd.getMaNv()).getMaTk();
            Object[] row = {
                hd.getMaHd(),
                TaiKhoanBUS.getInstance().getTaiKhoanByMaTk(ma_tk_nv).getTen(),
                TaiKhoanBUS.getInstance().getTaiKhoanByMaTk(ma_tk_kh).getTen(),
                hd.getTongTien(),
                
                
            };
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        */
        //</editor-fold>

        try{
            javax.swing.UIManager.setLookAndFeel(new FlatLightLaf());
        }catch(Exception ex){
            ex.printStackTrace();
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new QuanLyHoaDon().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Export;
    private javax.swing.JButton jButton_Refresh;
    private javax.swing.JButton jButton_Sua;
    private javax.swing.JButton jButton_Xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_TimKiem;
    // End of variables declaration//GEN-END:variables
}
