/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.List;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

import com.github.weisj.jsvg.nodes.Image;

import BUS.BUSManager;
import DTO.ThuocDTO;
import test.SuaThuocDialog;
import view.SuaThuocForm;
import view.ThongTinThuocForm;

/**
 *
 * @author Admin
 */
public class ThuocForm1 extends javax.swing.JFrame {

    /**
     * Creates new form ThuocForm
     */
    public static javax.swing.table.DefaultTableModel model;

    public ThuocForm1() {
        initComponents();
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plus.png")));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/wrench.png")));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/remove.png")));
        btnTimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png")));

        model = (javax.swing.table.DefaultTableModel) tblThuoc.getModel();

        // lấy data từ db
        loadData();

        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnInfo = new javax.swing.JButton();
        btnImport = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        btnThuoctinh = new javax.swing.JButton();
        jComboBox4 = new javax.swing.JComboBox<>();
        btnTimkiem = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThuoc = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnThem.setBackground(new java.awt.Color(80, 80, 80));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plus.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(80, 80, 80));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/wrench.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(80, 80, 80));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/remove.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnInfo.setBackground(new java.awt.Color(80, 80, 80));
        btnInfo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInfo.setForeground(new java.awt.Color(255, 255, 255));
        btnInfo.setText("Info");
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        btnImport.setBackground(new java.awt.Color(80, 80, 80));
        btnImport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnImport.setForeground(new java.awt.Color(255, 255, 255));
        btnImport.setText("Import");

        btnExport.setBackground(new java.awt.Color(80, 80, 80));
        btnExport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExport.setForeground(new java.awt.Color(255, 255, 255));
        btnExport.setText("Export");

        btnThuoctinh.setBackground(new java.awt.Color(80, 80, 80));
        btnThuoctinh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThuoctinh.setForeground(new java.awt.Color(255, 255, 255));
        btnThuoctinh.setText("Thuộc tính");

        jComboBox4.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox4.setForeground(new java.awt.Color(0, 0, 0));

        btnTimkiem.setBackground(new java.awt.Color(255, 255, 255));
        btnTimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        btnTimkiem.setBorderPainted(false);
        btnTimkiem.setFocusPainted(false);
        btnTimkiem.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemActionPerformed(evt);
            }
        });

        jTextField4.setBackground(new java.awt.Color(255, 255, 255));
        jTextField4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImport, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnThuoctinh)
                .addGap(18, 18, 18)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnImport, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnExport, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                .addComponent(btnThuoctinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(btnTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9))
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(153, 255, 255));
        jPanel5.setToolTipText("");
        jPanel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel5.setName(""); // NOI18N

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("THÔNG TIN THUỐC");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(546, 546, 546)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setName("1"); // NOI18N

        tblThuoc.setBackground(new java.awt.Color(255, 255, 255));
        tblThuoc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblThuoc.setForeground(new java.awt.Color(0, 0, 0));
        tblThuoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã thuốc ", "Tên thuốc ", "Giá ", "Danh mục ", "Đơn vị tính", "nhà sản xuất", "Xuất xứ"
            }
        ));
        tblThuoc.setShowHorizontalLines(true);
        tblThuoc.setShowVerticalLines(true);
        jScrollPane1.setViewportView(tblThuoc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThemActionPerformed
        // int selectedRow = tblThuoc.getSelectedRow();
        // if (selectedRow == -1) {
        // JOptionPane.showMessageDialog(this, "Vui lòng chọn một thuốc cần sửa!");
        // return;
        // } // GEN-LAST:event_btnThemActionPerformed
        // Lấy dữ liệu từ hàng được chọn
        // String maThuoc = tblThuoc.getValueAt(selectedRow, 0).toString();
        // String tenThuoc = tblThuoc.getValueAt(selectedRow, 1).toString();
        // double gia = Double.parseDouble(model.getValueAt(selectedRow, 2).toString());
        // String danhMuc = tblThuoc.getValueAt(selectedRow, 3).toString();
        // String donViTinh = tblThuoc.getValueAt(selectedRow, 4).toString();
        // String nhaSanXuat = tblThuoc.getValueAt(selectedRow, 5).toString();
        // String xuatXu = tblThuoc.getValueAt(selectedRow, 6).toString();

        // Mở form Sửa và truyền dữ liệu sang
        // SuaThuocForm formSua = new SuaThuocForm("", "", 0, 0.0, "", "", "",
        // selectedRow);
        // formSua.setVisible(true);
        // this.dispose(); // nếu bạn muốn tắt form hiện tại
        // this.dispose();
        ThemThuocForm formThem = new ThemThuocForm(this);
        formThem.setVisible(true);
        loadData();
    }

    private void btnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnTimkiemActionPerformed
        String keyword = jTextField4.getText().trim().toLowerCase();
        DefaultTableModel model = (DefaultTableModel) tblThuoc.getModel();

        // Nếu người dùng không nhập gì thì hiển thị lại toàn bộ
        if (keyword.isEmpty()) {
            TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
            tblThuoc.setRowSorter(sorter);
            sorter.setRowFilter(null);
            return;
        }

        // Sử dụng TableRowSorter để lọc
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tblThuoc.setRowSorter(sorter);

        // Tìm theo cột Mã thuốc (0), Tên thuốc (1), Danh mục (3)
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 0, 1, 3));
    }// GEN-LAST:event_btnTimkiemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSuaActionPerformed
        int selectedRow = tblThuoc.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một thuốc cần sửa!");
            return;
        }

        int modelRow = tblThuoc.convertRowIndexToModel(selectedRow);
        int maThuoc = (int) model.getValueAt(modelRow, 0);
        ThuocDTO thuoc = BUSManager.thuocBUS.getThuocByMaThuoc(maThuoc);

        if (thuoc == null) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy thuốc này!");
            return;
        }

        // SuaThuocDialog dialog = new SuaThuocDialog(this, thuoc);
        // dialog.setVisible(true);
        SuaThuocForm suaForm = new SuaThuocForm(String.valueOf(maThuoc), thuoc.getTenThuoc(),
                thuoc.getGia().doubleValue(), String.valueOf(thuoc.getMaDmt()), thuoc.getDonViTinh(),
                thuoc.getNhaSanXuat(), thuoc.getXuatXu(), this);
        suaForm.setVisible(true);

        // String maThuoc = tblThuoc.getValueAt(selectedRow, 0).toString();
        // String tenThuoc = tblThuoc.getValueAt(selectedRow, 1).toString();
        // double gia = Double.parseDouble(tblThuoc.getValueAt(selectedRow,
        // 2).toString());
        // String danhMuc = tblThuoc.getValueAt(selectedRow, 3).toString();
        // String donViTinh = tblThuoc.getValueAt(selectedRow, 4).toString();
        // String nhaSanXuat = tblThuoc.getValueAt(selectedRow, 5).toString();
        // String xuatXu = tblThuoc.getValueAt(selectedRow, 6).toString();

        // new SuaThuocForm(maThuoc, tenThuoc, gia, danhMuc, donViTinh, nhaSanXuat,
        // xuatXu, selectedRow).setVisible(true);
        // this.dispose();
    }// GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnXoaActionPerformed
        // Lấy hàng đang được chọn trong bảng
        int selectedRow = tblThuoc.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                    "Vui lòng chọn thuốc cần xóa!",
                    "Thông báo",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xoá thuốc này?", "Xác nhận",
                JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION)
            return;

        int modelRow = tblThuoc.convertRowIndexToModel(selectedRow);
        int maThuoc = (Integer) model.getValueAt(modelRow, 0);

        if (BUSManager.thuocBUS.deleteThuoc(maThuoc)) {
            JOptionPane.showMessageDialog(this, "Đã xoá thành công!");
            loadData();
        } else {
            JOptionPane.showMessageDialog(this, "Không thể xoá!");
        }
    }

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnInfoActionPerformed
        int selectedRow = tblThuoc.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn thuốc cần xem thông tin!");
            return;
        }

        // Lấy thông tin thuốc từ hàng được chọn
        String maThuoc = tblThuoc.getValueAt(selectedRow, 0).toString();
        String tenThuoc = tblThuoc.getValueAt(selectedRow, 1).toString();
        double gia = Double.parseDouble(tblThuoc.getValueAt(selectedRow, 2).toString());
        String danhMuc = tblThuoc.getValueAt(selectedRow, 3).toString();
        String donViTinh = tblThuoc.getValueAt(selectedRow, 4).toString();
        String nhaSanXuat = tblThuoc.getValueAt(selectedRow, 5).toString();
        String xuatXu = tblThuoc.getValueAt(selectedRow, 6).toString();

        // Mở form thông tin thuốc
        ThongTinThuocForm infoForm = new ThongTinThuocForm(maThuoc, tenThuoc, gia, danhMuc, donViTinh, nhaSanXuat,
                xuatXu);
        infoForm.setVisible(true);
    }// GEN-LAST:event_btnInfoActionPerformed

    public void loadData() {
        model.setRowCount(0);
        List<ThuocDTO> list = BUSManager.thuocBUS.getListThuoc();
        if (list == null)
            return;

        for (ThuocDTO t : list) {

            Object[] row = {
                    t.getMaThuoc(),
                    t.getTenThuoc(),
                    t.getGia(),
                    t.getMaDmt(),
                    t.getDonViTinh(),
                    t.getNhaSanXuat(),
                    t.getXuatXu(),
            };
            model.addRow(row);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThuocForm1.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThuocForm1.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThuocForm1.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThuocForm1.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnImport;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThuoctinh;
    private javax.swing.JButton btnTimkiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTable tblThuoc;
    // End of variables declaration//GEN-END:variables
}
