/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.List;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

import java.awt.Color;
import java.awt.Image;
import javax.swing.*;
import com.formdev.flatlaf.*;
import com.formdev.flatlaf.extras.*;

import BUS.BUSManager;
import DTO.ThuocDTO;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.table.TableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import view.Dialog.ImageDialog;
import view.Dialog.SuaThuocDialog;
import view.Dialog.ThemThuocDialog;

/**
 *
 * @author Admin
 */
public class ThuocForm1 extends javax.swing.JFrame {

    /**
     * Creates new form ThuocForm
     */
    public static javax.swing.table.DefaultTableModel model;

    public ThuocForm1() {
        initComponents();

        model = (javax.swing.table.DefaultTableModel) tblThuoc.getModel();

        // lấy data từ db
        loadData();

        setLocationRelativeTo(null);

        jTextField4.setText("");
        jTextField4.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                search();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                search();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                search();
            }

            private void search() {
                String text = jTextField4.getText().trim();
                if (text.isEmpty()) {
                    loadData();
                } else {
                    loadData(text);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        // btnInfo = new javax.swing.JButton();
        btnImport = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        btnThuoctinh = new javax.swing.JButton();
        jComboBox4 = new javax.swing.JComboBox<>();
        // btnTimkiem = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThuoc = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.putClientProperty(FlatClientProperties.STYLE, ""
                + "background: #FFFFFF;"
                + "borderWidth: 0;"
                + "focusWidth: 0;"
                + "innerFocusWidth: 0;"
                + "shadowWidth: 0;"
                + "arc: 8;"
                + "selectedBackground: #EBEBEB;");
        btnThem.setIcon(new FlatSVGIcon("image/add.svg", 40, 40));
        btnThem.setHorizontalTextPosition(SwingConstants.CENTER);
        btnThem.setVerticalTextPosition(SwingConstants.BOTTOM);
        btnThem.setHorizontalAlignment(SwingConstants.CENTER);
        btnThem.setIconTextGap(5);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.putClientProperty(FlatClientProperties.STYLE, ""
                + "background: #FFFFFF;"
                + "borderWidth: 0;"
                + "focusWidth: 0;"
                + "innerFocusWidth: 0;"
                + "shadowWidth: 0;"
                + "arc: 8;"
                + "selectedBackground: #EBEBEB;");
        btnSua.setIcon(new FlatSVGIcon("image/update.svg", 40, 40));
        btnSua.setHorizontalTextPosition(SwingConstants.CENTER);
        btnSua.setVerticalTextPosition(SwingConstants.BOTTOM);
        btnSua.setHorizontalAlignment(SwingConstants.CENTER);
        btnSua.setIconTextGap(5);
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.putClientProperty(FlatClientProperties.STYLE, ""
                + "background: #FFFFFF;"
                + "borderWidth: 0;"
                + "focusWidth: 0;"
                + "innerFocusWidth: 0;"
                + "shadowWidth: 0;"
                + "arc: 8;"
                + "selectedBackground: #EBEBEB;");
        btnXoa.setIcon(new FlatSVGIcon("image/delete.svg", 40, 40));
        btnXoa.setHorizontalTextPosition(SwingConstants.CENTER);
        btnXoa.setVerticalTextPosition(SwingConstants.BOTTOM);
        btnXoa.setHorizontalAlignment(SwingConstants.CENTER);
        btnXoa.setIconTextGap(5);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        // btnInfo.setBackground(new java.awt.Color(80, 80, 80));
        // btnInfo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        // btnInfo.setForeground(new java.awt.Color(255, 255, 255));
        // btnInfo.setText("Info");

        btnImport.setBackground(new java.awt.Color(80, 80, 80));
        btnImport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnImport.setForeground(new java.awt.Color(255, 255, 255));
        btnImport.setText("Xem ảnh");
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                // btnImportActionPerformed(evt);
                btnXemAnhActionPerformed(evt);
            }
        });

        btnExport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExport.setText("Export");
        btnExport.putClientProperty(FlatClientProperties.STYLE, ""
                + "background: #FFFFFF;"
                + "borderWidth: 0;"
                + "focusWidth: 0;"
                + "innerFocusWidth: 0;"
                + "shadowWidth: 0;"
                + "arc: 8;"
                + "selectedBackground: #EBEBEB;");
        btnExport.setIcon(new FlatSVGIcon("image/export.svg", 50, 50));
        btnExport.setHorizontalTextPosition(SwingConstants.CENTER);
        btnExport.setVerticalTextPosition(SwingConstants.BOTTOM);
        btnExport.setHorizontalAlignment(SwingConstants.CENTER);
        btnExport.setIconTextGap(5);
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        btnThuoctinh.setBackground(Color.BLACK);
        btnThuoctinh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThuoctinh.setForeground(new java.awt.Color(255, 255, 255));
        btnThuoctinh.setText("Làm mới");
        btnThuoctinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThuoctinhActionPerformed(evt);
            }
        });

        // btnTimkiem.setIcon(new
        // javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); //
        // NOI18N
        // btnTimkiem.setBorderPainted(false);
        // btnTimkiem.setFocusPainted(false);
        // btnTimkiem.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        // btnTimkiem.addActionListener(new java.awt.event.ActionListener() {
        // public void actionPerformed(java.awt.event.ActionEvent evt) {
        // btnTimkiemActionPerformed(evt);
        // }
        // });

        jTextField4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField4.setForeground(Color.BLACK);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 103,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 109,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 109,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                // .addComponent(btnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 85,
                                //         javax.swing.GroupLayout.PREFERRED_SIZE)
                                // .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnImport, javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, 102,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                // .addComponent(btnThuoctinh)
                                .addComponent(btnThuoctinh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                // .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                // .addComponent(btnTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                // javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 131,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(228, Short.MAX_VALUE)));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel3Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout
                                                        .createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addGroup(jPanel3Layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(btnThem,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 84,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(btnSua,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 84,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(btnXoa,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 84,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                // .addComponent(btnInfo,
                                                                //         javax.swing.GroupLayout.PREFERRED_SIZE, 84,
                                                                //         javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(btnImport,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 84,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                        .addContainerGap()
                                                        .addGroup(jPanel3Layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                .addComponent(btnExport,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE, 84,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(btnThuoctinh,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE))))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel3Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jTextField4,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 58,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                jPanel3Layout.createSequentialGroup()
                                                        // .addComponent(btnTimkiem,
                                                        // javax.swing.GroupLayout.PREFERRED_SIZE, 58,
                                                        // javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        // .addGap(9, 9, 9)
                                                        )
                                                        .addComponent(jComboBox4,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 58,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(9, Short.MAX_VALUE)));

        jPanel5.setBackground(new java.awt.Color(153, 255, 255));
        jPanel5.setToolTipText("");
        jPanel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel5.setName(""); // NOI18N

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÔNG TIN THUỐC");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setName("1"); // NOI18N

        tblThuoc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblThuoc.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null }
                },
                new String[] {
                        "Mã thuốc ", "Tên thuốc ", "Giá ", "Danh mục ", "Đơn vị tính", "nhà sản xuất", "Xuất xứ",
                        "Url Ảnh", "Số Lượng Hiện Có"
                }));
        tblThuoc.setShowHorizontalLines(true);
        tblThuoc.setShowVerticalLines(true);
        jScrollPane1.setViewportView(tblThuoc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                                .addGap(12, 12, 12)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThuoctinhActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThuoctinhActionPerformed
        // TODO add your handling code here:
        loadData();
    }// GEN-LAST:event_btnThuoctinhActionPerformed

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnImportActionPerformed
        
    }// GEN-LAST:event_btnImportActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnExportActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Chọn nơi lưu file");
        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            String filePath = fileChooser.getSelectedFile().getAbsolutePath();
            if (!filePath.endsWith(".xlxs")) {
                filePath += ".xlxs";
            }
            export(tblThuoc, filePath);
        }
    }// GEN-LAST:event_btnExportActionPerformed

    private void export(JTable jTable, String filePath) {
        try (Workbook workbook = new XSSFWorkbook()) {
            Sheet sheet = workbook.createSheet("Danh sách Danh Mục Thuốc");
            TableModel model = jTable.getModel();

            Row header = sheet.createRow(0);
            for (int i = 0; i < model.getColumnCount(); i++) {
                Cell cell = header.createCell(i);
                cell.setCellValue(model.getColumnName(i));
            }

            for (int i = 0; i < model.getRowCount(); i++) {
                Row row = sheet.createRow(i + 1);
                for (int j = 0; j < model.getColumnCount(); j++) {
                    Object value = model.getValueAt(i, j);
                    row.createCell(j).setCellValue(value != null ? value.toString() : "");
                }
            }
            try (FileOutputStream fos = new FileOutputStream(filePath)) {
                workbook.write(fos);
            }

            JOptionPane.showMessageDialog(null, "Xuất file Excel thành công");
        } catch (IOException ex) {
            System.out.println("view.DanhMucThuocForm1.export()");
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Lỗi xuất file Excel");
        }
    }

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThemActionPerformed
        ThemThuocDialog dialog = new ThemThuocDialog(this);
        dialog.setVisible(true);
        if (dialog.isConfirmed()) {
            BUSManager.thuocBUS.addThuoc(dialog.getThuoc());
            loadData();
        }
    }

    private void btnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnTimkiemActionPerformed
        String keyword = jTextField4.getText().trim().toLowerCase();
        DefaultTableModel model = (DefaultTableModel) tblThuoc.getModel();

        // Nếu người dùng không nhập gì thì hiển thị lại toàn bộ
        if (keyword.isEmpty()) {
            TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
            tblThuoc.setRowSorter(sorter);
            sorter.setRowFilter(null);
            return;
        }

        // Sử dụng TableRowSorter để lọc
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tblThuoc.setRowSorter(sorter);

        // Tìm theo cột Mã thuốc (0), Tên thuốc (1), Danh mục (3)
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 0, 1, 3));
    }// GEN-LAST:event_btnTimkiemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSuaActionPerformed
        int selectedRow = tblThuoc.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một thuốc cần sửa!");
            return;
        }

        int modelRow = tblThuoc.convertRowIndexToModel(selectedRow);
        int maThuoc = (int) model.getValueAt(modelRow, 0);
        ThuocDTO thuoc = BUSManager.thuocBUS.getThuocByMaThuoc(maThuoc);

        if (thuoc == null) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy thuốc này!");
            return;
        }

        SuaThuocDialog dialog = new SuaThuocDialog(this, thuoc);
        dialog.setVisible(true);

        if (dialog.isConfirmed()) {
            BUSManager.thuocBUS.updateThuoc(dialog.getThuoc());
            loadData();
        }
    }// GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnXoaActionPerformed
        // Lấy hàng đang được chọn trong bảng
        int selectedRow = tblThuoc.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                    "Vui lòng chọn thuốc cần xóa!",
                    "Thông báo",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xoá thuốc này?", "Xác nhận",
                JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION)
            return;

        int modelRow = tblThuoc.convertRowIndexToModel(selectedRow);
        int maThuoc = (Integer) model.getValueAt(modelRow, 0);

        if (BUSManager.thuocBUS.deleteThuoc(maThuoc)) {
            JOptionPane.showMessageDialog(this, "Đã xoá thành công!");
            loadData();
        } else {
            JOptionPane.showMessageDialog(this, "Không thể xoá!");
        }
    }

    private void btnXemAnhActionPerformed(java.awt.event.ActionEvent evt) {
        int selectedRow = tblThuoc.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn thuốc cần xem ảnh!");
            return;
        }

        new ImageDialog(this, String.valueOf(tblThuoc.getValueAt(selectedRow, 1)),
                String.valueOf(tblThuoc.getValueAt(selectedRow, 7)));
    }

    public void loadData() {
        model.setRowCount(0);
        List<ThuocDTO> list = BUSManager.thuocBUS.getListThuoc();
        if (list == null)
            return;

        for (ThuocDTO t : list) {
            // lấy số lượng hiện có
            int sl_ton = BUSManager.loHangBUS.getSlTonByMaThuoc(t.getMaThuoc());

            Object[] row = {
                    t.getMaThuoc(),
                    t.getTenThuoc(),
                    t.getGia(),
                    t.getMaDmt(),
                    t.getDonViTinh(),
                    t.getNhaSanXuat(),
                    t.getXuatXu(),
                    t.getUrlAnh(),
                    sl_ton,
            };
            model.addRow(row);
        }
    }

    public void loadData(String ten_thuoc) {
        model.setRowCount(0);
        List<ThuocDTO> list = BUSManager.thuocBUS.getListThuoc();
        if (list == null)
            return;

        for (ThuocDTO t : list) {
            if (t.getTenThuoc().toLowerCase().contains(ten_thuoc.toLowerCase())) {
                // lấy số lượng hiện có
                int sl_ton = BUSManager.loHangBUS.getSlTonByMaThuoc(t.getMaThuoc());

                Object[] row = {
                        t.getMaThuoc(),
                        t.getTenThuoc(),
                        t.getGia(),
                        t.getMaDmt(),
                        t.getDonViTinh(),
                        t.getNhaSanXuat(),
                        t.getXuatXu(),
                        t.getUrlAnh(),
                        sl_ton,
                };
                model.addRow(row);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnImport;
    // private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThuoctinh;
    // private javax.swing.JButton btnTimkiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTable tblThuoc;
    // End of variables declaration//GEN-END:variables
}
